SELECT  FROM CITY 
WHERE COUNTRYCODE = 'USA' 
  AND POPULATION  100000;
SELECT NAME FROM CITY
WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;
SELECT * FROM CITY
  WHERE ID = 1661;
SELECT * FROM CITY
  WHERE ID = 1661;
